apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: load-tester
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: infrastructure/charts/load-tester
    repoURL: git@github.com:oleksii-kryvoruchko/devops-playground.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
